### ISSUE TITLE
日志显示以及安装依赖建议

### ISSUE THREAD

**Issue by nkym233** [SuperManito/Arcadia#4]
### This function solves the problem (这个功能解决的问题)
可以在定时任务页面加一个最近一次日志的入口，方便查看日志。
依赖安装可视化，在网页可直接选择需要安装的依赖。
感谢！！

**Comment by SuperManito** [comment]
> ### This function solves the problem (这个功能解决的问题)
> 可以在定时任务页面加一个最近一次日志的入口，方便查看日志。 依赖安装可视化，在网页可直接选择需要安装的依赖。 感谢！！

1. "历史" 按钮就是你描述的查看最近一次日志的功能
2. 依赖安装可视化与定时表达式可视化的性质是一样的，就是会的人用不到、不会的人看着迷糊，未来不会添加此功能，除非有其它更好的解决方案
